//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKDILDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chiffre_affaires
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public string Num_facture { get; set; }
        public System.DateTime Date_facture { get; set; }
        public string Client { get; set; }
        public string Objet { get; set; }
        public decimal Montant_HT { get; set; }
        public int Taux { get; set; }
        public decimal Montant_TVA { get; set; }
        public decimal Montant_TTC { get; set; }
        public string Mode_reglement { get; set; }
        public System.DateTime Date_reglement { get; set; }
        public int Id_instance { get; set; }
    
        public virtual Instance_declaration Instance_declaration { get; set; }
    }
}
