//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKDILDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Declaration_totaux
    {
        public int Id { get; set; }
        public Nullable<decimal> Totale_TVA_exigible { get; set; }
        public Nullable<decimal> Totale_TVA_deductible { get; set; }
        public Nullable<decimal> Credit_N1 { get; set; }
        public Nullable<int> Id_instance { get; set; }
    
        public virtual Instance_declaration Instance_declaration { get; set; }
    }
}
