//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKDILDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deduction
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public string Num_facture { get; set; }
        public System.DateTime Date_facture { get; set; }
        public string Fournisseur { get; set; }
        public int IF_fournisseur { get; set; }
        public string Biens_services { get; set; }
        public decimal Montant_HT { get; set; }
        public int Taux { get; set; }
        public decimal Montant_TVA { get; set; }
        public decimal Montant_TTC { get; set; }
        public string Libelle_paiment { get; set; }
        public System.DateTime Date_paiment { get; set; }
        public string Mode_paiment { get; set; }
        public int ICE { get; set; }
        public int Id_instance { get; set; }
    
        public virtual Instance_declaration Instance_declaration { get; set; }
    }
}
