//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKDILDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entreprise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entreprise()
        {
            this.Identificateur_entreprise = new HashSet<Identificateur_entreprise>();
        }
    
        public int Id { get; set; }
        public string AdminId { get; set; }
        public string Raison_sociale { get; set; }
        public string Forme_juridique { get; set; }
        public string Objet { get; set; }
        public int IF { get; set; }
        public int ICE { get; set; }
        public int RC { get; set; }
        public int TP { get; set; }
        public string CIN { get; set; }
        public string Siege_sociale { get; set; }
        public string Ville { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Identificateur_entreprise> Identificateur_entreprise { get; set; }
    }
}
