//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKDILDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identificateur_entreprise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Identificateur_entreprise()
        {
            this.Instance_declaration = new HashSet<Instance_declaration>();
        }
    
        public int Id { get; set; }
        public int Id_entreprise { get; set; }
        public Nullable<decimal> Credit_N1 { get; set; }
        public int Annee { get; set; }
        public string Encaissement_debit { get; set; }
        public string Mois_trimestre { get; set; }
    
        public virtual Entreprise Entreprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instance_declaration> Instance_declaration { get; set; }
    }
}
