//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKDILDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instance_declaration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instance_declaration()
        {
            this.Chiffre_affaires = new HashSet<Chiffre_affaires>();
            this.Declaration_totaux = new HashSet<Declaration_totaux>();
            this.Deduction = new HashSet<Deduction>();
            this.Ventilation_CA_imposable = new HashSet<Ventilation_CA_imposable>();
            this.Ventilation_CA_totale = new HashSet<Ventilation_CA_totale>();
            this.Ventilation_deduction = new HashSet<Ventilation_deduction>();
        }
    
        public int Id { get; set; }
        public int Mois { get; set; }
        public int Id_Identificateur_entreprise { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chiffre_affaires> Chiffre_affaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Declaration_totaux> Declaration_totaux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deduction> Deduction { get; set; }
        public virtual Identificateur_entreprise Identificateur_entreprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventilation_CA_imposable> Ventilation_CA_imposable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventilation_CA_totale> Ventilation_CA_totale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventilation_deduction> Ventilation_deduction { get; set; }
    }
}
