//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKDILDataManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AKADILDataEntities : DbContext
    {
        public AKADILDataEntities()
            : base("name=AKADILDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Biens_services> Biens_services { get; set; }
        public virtual DbSet<Chiffre_affaires> Chiffre_affaires { get; set; }
        public virtual DbSet<CODE_TAUX_CHARGES> CODE_TAUX_CHARGES { get; set; }
        public virtual DbSet<CODE_TAUX_PRODUITS> CODE_TAUX_PRODUITS { get; set; }
        public virtual DbSet<Declaration_totaux> Declaration_totaux { get; set; }
        public virtual DbSet<Deduction> Deduction { get; set; }
        public virtual DbSet<Entreprise> Entreprise { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<Identificateur_entreprise> Identificateur_entreprise { get; set; }
        public virtual DbSet<Instance_declaration> Instance_declaration { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Ventilation_CA_imposable> Ventilation_CA_imposable { get; set; }
        public virtual DbSet<Ventilation_CA_totale> Ventilation_CA_totale { get; set; }
        public virtual DbSet<Ventilation_deduction> Ventilation_deduction { get; set; }
    }
}
