//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AKDILDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventilation_CA_totale
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public int Id_instance { get; set; }
    
        public virtual Instance_declaration Instance_declaration { get; set; }
    }
}
